//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Middleware.ServiceJava {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://facade.projetmgmt.exia.com/", ConfigurationName="ServiceJava.ProjetEndpoint")]
    public interface ProjetEndpoint {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément textName de l'espace de noms  n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.projetmgmt.exia.com/ProjetEndpoint/decodageRequest", ReplyAction="http://facade.projetmgmt.exia.com/ProjetEndpoint/decodageResponse")]
        Middleware.ServiceJava.decodageResponse decodage(Middleware.ServiceJava.decodageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class decodageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="decodage", Namespace="http://facade.projetmgmt.exia.com/", Order=0)]
        public Middleware.ServiceJava.decodageRequestBody Body;
        
        public decodageRequest() {
        }
        
        public decodageRequest(Middleware.ServiceJava.decodageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class decodageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string textName;
        
        public decodageRequestBody() {
        }
        
        public decodageRequestBody(string textName) {
            this.textName = textName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class decodageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="decodageResponse", Namespace="http://facade.projetmgmt.exia.com/", Order=0)]
        public Middleware.ServiceJava.decodageResponseBody Body;
        
        public decodageResponse() {
        }
        
        public decodageResponse(Middleware.ServiceJava.decodageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class decodageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text;
        
        public decodageResponseBody() {
        }
        
        public decodageResponseBody(string text) {
            this.text = text;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProjetEndpointChannel : Middleware.ServiceJava.ProjetEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjetEndpointClient : System.ServiceModel.ClientBase<Middleware.ServiceJava.ProjetEndpoint>, Middleware.ServiceJava.ProjetEndpoint {
        
        public ProjetEndpointClient() {
        }
        
        public ProjetEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjetEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjetEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjetEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Middleware.ServiceJava.decodageResponse Middleware.ServiceJava.ProjetEndpoint.decodage(Middleware.ServiceJava.decodageRequest request) {
            return base.Channel.decodage(request);
        }
        
        public string decodage(string textName) {
            Middleware.ServiceJava.decodageRequest inValue = new Middleware.ServiceJava.decodageRequest();
            inValue.Body = new Middleware.ServiceJava.decodageRequestBody();
            inValue.Body.textName = textName;
            Middleware.ServiceJava.decodageResponse retVal = ((Middleware.ServiceJava.ProjetEndpoint)(this)).decodage(inValue);
            return retVal.Body.text;
        }
    }
}
